export const MUTATION_G_SHOW_ALERT = 'MUTATION_G_SHOW_ALERT';
export const MUTATION_G_CLOSE_ALERT = 'MUTATION_G_CLOSE_ALERT';
export const MUTATION_G_SHOW_NEXT_ALERT = 'MUTATION_G_SHOW_NEXT_ALERT';


export const MUTATION_G_UPDATE_THEME_COLOR = 'MUTATION_G_UPDATE_THEME_COLOR';
export const MUTATION_G_UPDATE_THEME_IS_DARK = 'MUTATION_G_UPDATE_THEME_IS_DARK';

export const MUTATION_G_INIT_THEME_COLOR = 'MUTATION_G_INIT_THEME_COLOR';
export const MUTATION_G_INIT_THEME_IS_DARK = 'MUTATION_G_INIT_THEME_IS_DARK';


export const MUTATION_G_ATTACH_VUE = 'MUTATION_G_I_ATTACH_VUE';

export const MUTATION_G_ADD_KEY_UP = 'MUTATION_G_ADD_KEY_UP';
export const MUTATION_G_REMOVE_KEY_UP = 'MUTATION_G_REMOVE_KEY_UP';
