export const MUTATION_ALERT_ERROR = 'MUTATION_ALERT_ERROR';
export const MUTATION_ALERT_WARN = 'MUTATION_ALERT_WARN';
export const MUTATION_ALERT_SUCCESS = 'MUTATION_ALERT_SUCCESS';
export const MUTATION_ALERT_CLOSE = 'MUTATION_ALERT_CLOSE';

export const MUTATION_G_UPDATE_THEME_COLOR = 'MUTATION_G_UPDATE_THEME_COLOR';
export const MUTATION_G_UPDATE_THEME_IS_DARK = 'MUTATION_G_UPDATE_THEME_IS_DARK';

export const MUTATION_G_INIT_THEME_COLOR = 'MUTATION_G_INIT_THEME_COLOR';
export const MUTATION_G_INIT_THEME_IS_DARK = 'MUTATION_G_INIT_THEME_IS_DARK';


export const MUTATION_G_ATTACH_VUE = 'MUTATION_G_I_ATTACH_VUE';

